[TAIPY]

[DATA_NODE.initial_dataset]
storage_type = "csv"
scope = "GLOBAL:SCOPE"
path = "df_aapl.csv"

[DATA_NODE.cleaned_dataset]
scope = "GLOBAL:SCOPE"

[DATA_NODE.model_output]
storage_type = "pickle"
scope = "GLOBAL:SCOPE"

[DATA_NODE.predictions]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[TASK.predict]
inputs = [ "model_output:SECTION" ]
outputs = [ "predictions:SECTION" ]
function = "create_mod_core.predict:function"
skippable = "True:bool"

[TASK.clean_data_task]
inputs = [ "initial_dataset:SECTION",]
function = "create_mod_core.clean_data:function"
outputs = [ "cleaned_dataset:SECTION",]
skippable = "True:bool"

[TASK.model_retraining_task]
inputs = [ "cleaned_dataset:SECTION",]
function = "create_mod_core.retrained_model:function"
outputs = [ "model_output:SECTION",]
skippable = "True:bool"

[PIPELINE.model_retraining_pipeline]
tasks = [
  "clean_data_task:SECTION",
  "model_retraining_task:SECTION",
  "predict:SECTION"
]

[SCENARIO.stock]
pipelines = [ "model_retraining_pipeline:SECTION" ]
